// Code generated by MockGen. DO NOT EDIT.
// Source: permission_client.go
//
// Generated by this command:
//
//	mockgen -source=permission_client.go -destination=./mock/permission_client_mock.go -package=authmock
//

// Package authmock is a generated GoMock package.
package authmock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPermissionClient is a mock of PermissionClient interface.
type MockPermissionClient struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionClientMockRecorder
	isgomock struct{}
}

// MockPermissionClientMockRecorder is the mock recorder for MockPermissionClient.
type MockPermissionClientMockRecorder struct {
	mock *MockPermissionClient
}

// NewMockPermissionClient creates a new mock instance.
func NewMockPermissionClient(ctrl *gomock.Controller) *MockPermissionClient {
	mock := &MockPermissionClient{ctrl: ctrl}
	mock.recorder = &MockPermissionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionClient) EXPECT() *MockPermissionClientMockRecorder {
	return m.recorder
}

// AddPolicy mocks base method.
func (m *MockPermissionClient) AddPolicy(ctx context.Context, userID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicy", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPolicy indicates an expected call of AddPolicy.
func (mr *MockPermissionClientMockRecorder) AddPolicy(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicy", reflect.TypeOf((*MockPermissionClient)(nil).AddPolicy), ctx, userID, resource, action)
}

// AddPolicyIfNotExists mocks base method.
func (m *MockPermissionClient) AddPolicyIfNotExists(ctx context.Context, userID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicyIfNotExists", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPolicyIfNotExists indicates an expected call of AddPolicyIfNotExists.
func (mr *MockPermissionClientMockRecorder) AddPolicyIfNotExists(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicyIfNotExists", reflect.TypeOf((*MockPermissionClient)(nil).AddPolicyIfNotExists), ctx, userID, resource, action)
}

// CheckPermission mocks base method.
func (m *MockPermissionClient) CheckPermission(ctx context.Context, userID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPermissionClientMockRecorder) CheckPermission(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPermissionClient)(nil).CheckPermission), ctx, userID, resource, action)
}

// Close mocks base method.
func (m *MockPermissionClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPermissionClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPermissionClient)(nil).Close))
}

// RemovePolicy mocks base method.
func (m *MockPermissionClient) RemovePolicy(ctx context.Context, userID, resource, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePolicy", ctx, userID, resource, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePolicy indicates an expected call of RemovePolicy.
func (mr *MockPermissionClientMockRecorder) RemovePolicy(ctx, userID, resource, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicy", reflect.TypeOf((*MockPermissionClient)(nil).RemovePolicy), ctx, userID, resource, action)
}
