apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-gin
  labels:
    app: web-server-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-gin
  template:
    metadata:
      labels:
        app: web-server-gin
    spec:
      containers:
        - name: web-server-gin
          image: xomrkob/web-server-gin:1.1.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDRESS
              value: ":8080"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DATABASE_URL
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
