apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-gin
  labels:
    app: web-server-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-gin
  template:
    metadata:
      labels:
        app: web-server-gin
    spec:
      containers:
        - name: web-server-gin
          image: xomrkob/web-server-gin:1.1.18
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_ADDR
              value: ":8080"
            - name: DB_HOST
              value: postgresql.go-app.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "database1"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: go-app-secret
                  key: DB_USER
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
